### ISSUE TITLE
不会进入下一章节

### ISSUE THREAD

**Issue by ChunQiu2076** [yecaiyu1999/chaoxing#1]
第一章节刷完就卡住了，一直返回已完成
多用户多任务不行，进度提交不上

**Comment by yecaiyu1999** [comment]
那可能只能单任务吧。多用户单任务好像之前尝试没啥问题，按客户端来看，一个用户开两门课来刷他会停住一个，看来直接给他请求也会这样，最后一学期刷课，刷完了，不研究了，看你了大兄弟😄
